apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootapp2
  labels:
    app: springbootapp2
spec:
   replicas: 2
   strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
   selector:
     matchLabels:
      app: springbootapp2
   template:
     metadata:
      labels:
        app: springbootapp2
     spec:
         containers:
         - name: springbootapp2
           image: gauravbhutani30/devops:0.0.1.0
           ports:
           - containerPort: 8080
