apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootapp2
  labels:
    app: springbootapp2
spec:
   replicas: 4
   strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
   selector:
     matchLabels:
      app: springbootapp2
   template:
     metadata:
      labels:
        app: springbootapp2
     spec:
         containers:
         - name: springbootapp2
           image: gauravbhutani30/devops:${tagVersion}
           ports:
           - port: 8080
