apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
  labels:
    app: springboot
spec:
   replicas: 4
   strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
   selector:
     matchLabels:
      app: springbootapp
   template:
     metadata:
      labels:
        app: springboot
     spec:
         containers:
         - name: springboot
           image: gauravbhutani30/devops:tagVersion
           ports:
           - containerPort: 8080
