apiVersion: apps/v1
kind: Deployment
metadata:
  name: springtestapp
  labels:
    app: springapp
spec:
   replicas: 2
   strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
   selector:
     matchLabels:
      app: springtestapp
   template:
     metadata:
      labels:
        app: springtestapp
     spec:
         containers:
         - name: springtestapp
           image: gauravbhutani30/devops:tagVersion
           ports:
           - containerPort: 8080
