apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootapp1
  labels:
    app: springbootapp1
spec:
   replicas: 4
   strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
   selector:
     matchLabels:
      app: springbootapp1
   template:
     metadata:
      labels:
        app: springbootapp1
     spec:
         containers:
         - name: springbootapp1
           image: gauravbhutani30/devops:2082d6e2044408f9174f600f62998f8238e2e406
           ports:
           - port: 8080
