apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootapp1
  labels:
    app: springbootapp1
spec:
   replicas: 2
   strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
   selector:
     matchLabels:
      app: springbootapp1
   template:
     metadata:
      labels:
        app: springbootapp1
     spec:
         containers:
         - name: springbootapp1
           image: gauravbhutani30/devops:tagVersion
           ports:
           - containerPort: 8080
