apiVersion: v1
kind: Pod
metadata:
  name: springbootapp
  labels:
    app: springbootapp
spec:
  containers:
    - name: springbootapp
      image: gauravbhutani30/devops:tagVersion
      ports:
        - containerPort: 8080
