/*apiVersion: v1
kind: Pod
metadata:
  name: springbootapp
  labels:
    app: springbootapp
spec:
  containers:
    - name: springbootapp
      image: gauravbhutani30/devops:tagVersion
      ports:
        - containerPort: 8080
*/

apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootapp
  labels:
    app: springbootapp
spec:
   replicas: 1
   strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
   selector:
     matchLabels:
      app: springbootapp
   template:
     metadata:
      labels:
        app: springbootapp
     spec:
         containers:
         - name: springbootapp
           image: gauravbhutani30/devops:2082d6e2044408f9174f600f62998f8238e2e406
           ports:
           - port: 8080
